language: android
sudo: required
android:
  components:
    - build-tools-28.0.3
    - platforms-tools
  licences:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'intel-android-extra-license.+'
script:
- ./gradlew build
